### PR TITLE
Mca/get count points

### PR DESCRIPTION
**Pull request by mcast**
get_count_points looked a bit wonky, so I fixed it.
score

### CODE REVIEW

**Comment by mcast** [comment]
Sorry, I haven't fixed the tests.  They're not just running nice and easily out of the box with
```
PATH=/software/python-2.7.3/bin:$PATH sh ./run_tests.sh
```

**Comment by bewt85** [comment]
How odd about the tests.  Thinking about it I am normally working in a virtualenv and then fo a 'development' install:
```
virtualenv venv
. venv/bin/activate
pip install -r requirements.txt
python setup.py develop
```

Thanks for the bug fix as well btw; it cried when I tried running your fork.  Do you mind if I look at this on Saturday / Sunday?

**Comment by mcast** [comment]
No rush.

It cried because pasted hacked code and didn't run it in place, sorry.

**Comment by bewt85** [comment]
PS your graph is much nicer than mine :)

**Comment by mcast** [comment]
> PS your graph is much nicer than mine :)

Oh, which graph?  I recently started using [gnuplot](http://www.gnuplot.info/), suits me fine so far.

get_date_points was also broken, giving only points (5) for anything over 7 days old.

I fixed it (6c8f632d), graphed it and replaced with a smooth approximation:
date

**Comment by bewt85** [comment]
@mcast Thanks for your help.  The results look a little better without the weird kink in the scoring.  I've updated the example app: https://github-conglomerate.herokuapp.com/

**Pull request merged**
